### ISSUE TITLE
Build sdcard with xvdpu

### ISSUE THREAD

**Issue by Nunigan** [Xilinx/vck190-base-trd#1]
Hello

I got this error while making the sdcard with the xvdpu:

_make sdcard PFM=vck190_mipiRxSingle_hdmiTx OVERLAY=xvdpu
Build PetaLinux wic image for vck190_mipiRxSingle_hdmiTx - xvdpu
make -C petalinux/xilinx-vck190-base-trd wic PFM=vck190_mipiRxSingle_hdmiTx
make[1]: Entering directory '/media/nunigan/SSD2/vck190-base-trd/petalinux/xilinx-vck190-base-trd'
Build PetaLinux image
./trd-pl-cfg: 13: Syntax error: "(" unexpected
make[1]: *** [Makefile:68: images/linux/boot.scr] Error 2
make[1]: Leaving directory '/media/nunigan/SSD2/vck190-base-trd/petalinux/xilinx-vck190-base-trd'
make: *** [Makefile:71: petalinux/xilinx-vck190-base-trd/images/linux/petalinux-sdimage.wic.xz] Error 2_

Thanks for the help, Michael

**Comment by chkohn** [comment]
@Nunigan could you please check if https://github.com/Xilinx/vck190-base-trd/pull/2 fixes your issue? I'm assuming you are using dash or some other non-bash shell as default?

**Comment by Nunigan** [comment]
@chkohn Thanks, it worked with #2. Actually I am using bash.

**Comment by chkohn** [comment]
thanks for confirming, merged the PR.
