### ISSUE TITLE
Use bash instead of csh/tcsh

### ISSUE THREAD

**Issue by louiev-xlnx** [Xilinx/vck190-base-trd#4]
Some scripts in the XVDPU TRD use csh|tcsh.
![image](https://user-images.githubusercontent.com/94657816/163502306-99cc6762-a453-43a3-9afd-9e0a830bcae3.png)

Since csh|tcsh are not installed by default on Ubuntu, please change these scripts to use bash.

**Comment by xlinyg** [comment]
Hi, @louiev-xlnx 
Compiling AIE parts of XVDPU will need csh, we do not plan to update it as bash.
You can refer to the readme of XVDPU TRD in Vitis-AI, we have added this csh software requirement.
https://github.com/Xilinx/Vitis-AI/tree/master/dsa/XVDPU-TRD#32-software

**Comment by louiev-xlnx** [comment]
ok. thanks!
