### ISSUE TITLE
Are the examples models quantized?

### ISSUE THREAD

**Issue by DeepTrial** [Xilinx/vck190-base-trd#5]
rt, I wonder if the examples models are quantized. And if they are quantized, what quantization methods are they used? Symmetirc/Asymetric? uint8/int8?

**Comment by xlnx-yuxiz** [comment]
It's using the quantized model. Please check https://docs.xilinx.com/r/1.4.1-English/ug1414-vitis-ai/Quantizing-the-Model for detailed info about the quantization.

**Comment by chkohn** [comment]
@DeepTrial if your question is answered, please close the issue.

**Comment by chkohn** [comment]
@DeepTrial closing issue as question has been answered. Feel free to re-open if there are follow-up questions.
